theme: jekyll-theme-tactile

# jekyll-seo-tag
title:           " "
#tagline:
description:    "Masterâ€™s in Data Science Postgraduate Student at UKM. Data Enthusiast that actively augmenting knowledge and skill in data mining, analytic and machine learning"
#url:           https://yeetornghoo.github.io/
#author:        yeetornghoo
logo:           /docs/profile.png
